### ISSUE TITLE
Gas Optimization in Batch event

### ISSUE THREAD

**Issue by aodhgan** [pooltogether/pods-v3-contracts#12]
I dont think the block number is needed, since this is externally associated with the event.

https://github.com/pooltogether/pods-v3-contracts/blob/master/contracts/Pod.sol#L84

**Comment by aodhgan** [comment]
@kamescg

**Comment by kamescg** [comment]
@aodhgan Making a branch right now with this fix included - thank you for pointing this out.

**Comment by kamescg** [comment]
@aodhgan The reasoning for this originally (I believe) because I hadn't seen the documentation for easily getting a timestamp in TheGraph documentation, but to my understanding now is you can just use `event.block.timestamp` 🤦

Thanks for pointing this out - Going to make a PR with this and a few other updates shortly.

**Comment by aodhgan** [comment]
Nice, thanks!
